### ISSUE TITLE
TTFError, Cant figure it out 

### ISSUE THREAD

**Issue by adrijanb** [BjoernLudwigPTB/pyxml2pdf#4]
reportlab.pdfbase.ttfonts.TTFError: Can't open file "/usr/local/lib/python3.8/dist-packages/pyxml2pdf/styles/fonts/NewsGothicBT-Roman.ttf"

**Comment by adrijanb** [comment]
i am trying to generate a pdf using a pdf file

**Comment by BjoernLudwigPTB** [comment]
Please try and let me know, if it works now. If not, please include some more information about what exactly you are trying to do. (commands, expected and actual result)

**Comment by adrijanb** [comment]
Hey,

Ich schreib es dir vielleicht einfach ganz kurz in Deutsch. Leider erhalte ich immer noch einen Fehler, aber ich glaube, dass dieser nun aus deinen Changes hervorgeht. 

Folgender Fehler tritt nun auf:

```
    from input.properties import columns, font, fontsize  # type: ignore
ModuleNotFoundError: No module named 'input'
```

Ich versuche eine XML Datei in eine PDF zu generieren. Da ich zuvor noch Strings in meiner XML escapen muss. Mit diesem Tool funktioniert es einwandfrei, leider keine API (https://www.pdfconvertonline.com/index-simple.html). Daher suche ich gerade nach einer Lösung und diese schien mir erstmal sehr gut. Falls du die XML brauchst um zu testen, kann ich dir diese gerne senden und das gewünschte Resultat

**Comment by BjoernLudwigPTB** [comment]
Thanks for the effort to check if it is working. Yes please, stick to German as you like. I will answer in English though to allow international users and developers later to follow along easier. The errors finally should be resolved and everything should be working as expected and described in the docs and README. If your results do not look as expected from the start, yes please, send it over and I will have a look. For that purpose though, please open a discussion rather than an issue. I am glad that *pyxml2pdf* might be helpful to you.
